export enum ActionTypes {
  CreateEC2 = "AWS/CreateEC2",
  UpdateEC2 = "AWS/UpdateEC2",
  RemoveEC2 = "AWS/RemoveEC2",
  CreateVPC = "AWS/CreateVPC",
  UpdateVPC = "AWS/UpdateVPC",
  RemoveVPC = "AWS/RemoveVPC",
  CreateSubnet = "AWS/CreateSubnet",
  UpdateSubnet = "AWS/UpdateSubnet",
  RemoveSubnet = "AWS/RemoveSubnet",
  CreateRouteTable = "AWS/CreateRouteTable",
  UpdateRouteTable = "AWS/UpdateRouteTable",
  RemoveRouteTable = "AWS/RemoveRouteTable",
  CreateSecurityGroup = "AWS/CreateSecurityGroup",
  UpdateSecurityGroup = "AWS/UpdateSecurityGroup",
  RemoveSecurityGroup = "AWS/RemoveSecurityGroup",
  CreateInternetGateway = "AWS/CreateInternetGateway",
  UpdateInternetGateway = "AWS/UpdateInternetGateway",
  RemoveInternetGateway = "AWS/RemoveInternetGateway",

  CreateSample = "AWS/CreateSample",
}
